import type { CanonicalPrimitive, CityGeometryPlanningSource, CityMass, CityPlane, ExpoZonePlannerContext } from '../../types';

const CENTER_SPINE_GEOMETRY_SOURCE_FILE = 'src/modules/expo/runtime/planning/zones/center-spine/geometry.ts';
const CENTER_SKY_COMPASS_SOURCE_KIND = 'center-sky-compass-render-rig';
const SKY_MARKET_SPINE_SOURCE_KIND = 'sky-market-spine-render-rig';
const AI_REACTOR_CORE_SOURCE_KIND = 'ai-reactor-core-render-rig';

function createCenterSpinePlanningSource(
  sourceFunction: string,
  sourceKind: string,
): CityGeometryPlanningSource {
  return {
    safeEditSeam: CENTER_SPINE_GEOMETRY_SOURCE_FILE,
    sourceFile: CENTER_SPINE_GEOMETRY_SOURCE_FILE,
    sourceFunction,
    sourceKind,
  };
}

function isCenterSpinePlane(plane: CityPlane) {
  return Math.abs(plane.position[0]) <= 260 && plane.position[2] > -2200;
}

function isCenterSpineMass(mass: CityMass) {
  return Math.abs(mass.position[0]) <= 260 && mass.position[2] > -2200;
}

function buildSkyMarketSpineMasses(): CityMass[] {
  const center: [number, number, number] = [0, 0, -520];
  const accent = '#ffe08a';
  const podZs = [-390, -130, 130, 390];

  return [
    {
      color: '#141f2b',
      decorPolicy: 'none',
      id: 'sky-market-spine-primitive-rig',
      planningSource: createCenterSpinePlanningSource('buildSkyMarketSpineMasses', SKY_MARKET_SPINE_SOURCE_KIND),
      position: center,
      renderIntent: {
        emissive: accent,
        emissiveIntensity: 0.018,
        primitives: [
          {
            color: '#6d7d88',
            emissive: accent,
            emissiveIntensity: 0.012,
            kind: 'box',
            metalness: 0.12,
            physics: 'decorative',
            position: [0, 520, 0],
            roughness: 0.58,
            size: [820, 34, 1120],
          },
          {
            color: '#8799a6',
            emissive: accent,
            emissiveIntensity: 0.016,
            kind: 'box',
            metalness: 0.16,
            physics: 'decorative',
            position: [0, 900, 0],
            roughness: 0.5,
            size: [620, 30, 980],
          },
          {
            color: '#ffd766',
            emissive: accent,
            emissiveIntensity: 0.055,
            kind: 'box',
            metalness: 0.2,
            physics: 'decorative',
            position: [0, 542, 0],
            roughness: 0.28,
            size: [38, 10, 1080],
          },
          {
            color: '#ffd766',
            emissive: accent,
            emissiveIntensity: 0.05,
            kind: 'box',
            metalness: 0.2,
            physics: 'decorative',
            position: [0, 922, 0],
            roughness: 0.28,
            size: [28, 8, 930],
          },
          {
            color: '#91a5b0',
            emissive: accent,
            emissiveIntensity: 0.012,
            kind: 'box',
            metalness: 0.14,
            physics: 'decorative',
            position: [-450, 730, -420],
            roughness: 0.54,
            size: [70, 460, 70],
          },
          {
            color: '#91a5b0',
            emissive: accent,
            emissiveIntensity: 0.012,
            kind: 'box',
            metalness: 0.14,
            physics: 'decorative',
            position: [450, 730, -420],
            roughness: 0.54,
            size: [70, 460, 70],
          },
          {
            color: '#91a5b0',
            emissive: accent,
            emissiveIntensity: 0.012,
            kind: 'box',
            metalness: 0.14,
            physics: 'decorative',
            position: [-450, 730, 420],
            roughness: 0.54,
            size: [70, 460, 70],
          },
          {
            color: '#91a5b0',
            emissive: accent,
            emissiveIntensity: 0.012,
            kind: 'box',
            metalness: 0.14,
            physics: 'decorative',
            position: [450, 730, 420],
            roughness: 0.54,
            size: [70, 460, 70],
          },
          {
            color: '#243447',
            emissive: accent,
            emissiveIntensity: 0.018,
            height: 760,
            kind: 'cylinder',
            metalness: 0.2,
            physics: 'decorative',
            position: [-520, 680, 0],
            radialSegments: 18,
            radiusBottom: 30,
            radiusTop: 24,
            roughness: 0.38,
          },
          {
            color: '#243447',
            emissive: accent,
            emissiveIntensity: 0.018,
            height: 760,
            kind: 'cylinder',
            metalness: 0.2,
            physics: 'decorative',
            position: [520, 680, 0],
            radialSegments: 18,
            radiusBottom: 30,
            radiusTop: 24,
            roughness: 0.38,
          },
          ...podZs.flatMap((z): CanonicalPrimitive[] => [
            {
              color: '#24384a',
              emissive: accent,
              emissiveIntensity: 0.016,
              kind: 'box',
              metalness: 0.18,
              physics: 'decorative',
              position: [-380, 600, z],
              roughness: 0.46,
              size: [150, 116, 88],
            },
            {
              color: '#273c4e',
              emissive: accent,
              emissiveIntensity: 0.016,
              kind: 'box',
              metalness: 0.18,
              physics: 'decorative',
              position: [380, 600, z],
              roughness: 0.46,
              size: [150, 116, 88],
            },
            {
              color: '#f7d36b',
              emissive: accent,
              emissiveIntensity: 0.035,
              kind: 'box',
              metalness: 0.22,
              physics: 'decorative',
              position: [-380, 680, z + 1],
              roughness: 0.3,
              size: [132, 10, 10],
            },
            {
              color: '#f7d36b',
              emissive: accent,
              emissiveIntensity: 0.035,
              kind: 'box',
              metalness: 0.22,
              physics: 'decorative',
              position: [380, 680, z + 1],
              roughness: 0.3,
              size: [132, 10, 10],
            },
          ]),
        ],
        showCrownBeacon: false,
        showFrontWing: false,
        showHorizontalCap: false,
        showMegaVerticalSpines: false,
        showRearSpine: false,
        showSideFloorBands: false,
        showSideInset: false,
        showSignatureBand: false,
        skipBase: true,
      },
      role: 'structural',
      sections: ['middle'],
      size: [1, 1, 1],
    },
  ];
}

function buildAiReactorCoreMasses(): CityMass[] {
  const center: [number, number, number] = [-2200, 0, -520];
  const accent = '#6fffe9';

  return [
    {
      color: '#081d24',
      decorPolicy: 'none',
      id: 'ai-reactor-core-primitive-rig',
      planningSource: createCenterSpinePlanningSource('buildAiReactorCoreMasses', AI_REACTOR_CORE_SOURCE_KIND),
      position: center,
      renderIntent: {
        emissive: accent,
        emissiveIntensity: 0.024,
        primitives: [
          {
            color: '#203341',
            emissive: accent,
            emissiveIntensity: 0.014,
            height: 90,
            kind: 'cylinder',
            metalness: 0.18,
            physics: 'decorative',
            position: [0, 45, 0],
            radialSegments: 48,
            radiusBottom: 330,
            radiusTop: 280,
            roughness: 0.44,
          },
          {
            color: '#7dfff1',
            emissive: accent,
            emissiveIntensity: 0.07,
            height: 1680,
            kind: 'cylinder',
            metalness: 0.18,
            opacity: 0.74,
            physics: 'decorative',
            position: [0, 920, 0],
            radialSegments: 32,
            radiusBottom: 78,
            radiusTop: 46,
            roughness: 0.2,
            transparent: true,
          },
          {
            color: '#dffefb',
            emissive: accent,
            emissiveIntensity: 0.06,
            height: 36,
            kind: 'cylinder',
            metalness: 0.28,
            opacity: 0.88,
            physics: 'decorative',
            position: [0, 480, 0],
            radialSegments: 64,
            radiusBottom: 360,
            radiusTop: 320,
            roughness: 0.22,
            transparent: true,
          },
          {
            color: '#b8fff7',
            emissive: accent,
            emissiveIntensity: 0.055,
            height: 32,
            kind: 'cylinder',
            metalness: 0.26,
            opacity: 0.84,
            physics: 'decorative',
            position: [0, 880, 0],
            radialSegments: 64,
            radiusBottom: 460,
            radiusTop: 410,
            roughness: 0.24,
            transparent: true,
          },
          {
            color: '#a5fff4',
            emissive: accent,
            emissiveIntensity: 0.052,
            height: 28,
            kind: 'cylinder',
            metalness: 0.24,
            opacity: 0.78,
            physics: 'decorative',
            position: [0, 1280, 0],
            radialSegments: 64,
            radiusBottom: 540,
            radiusTop: 480,
            roughness: 0.26,
            transparent: true,
          },
          {
            color: '#3ddcca',
            emissive: accent,
            emissiveIntensity: 0.045,
            kind: 'box',
            metalness: 0.18,
            physics: 'decorative',
            position: [0, 890, 0],
            roughness: 0.32,
            size: [980, 12, 18],
          },
          {
            color: '#3ddcca',
            emissive: accent,
            emissiveIntensity: 0.045,
            kind: 'box',
            metalness: 0.18,
            physics: 'decorative',
            position: [0, 910, 0],
            roughness: 0.32,
            size: [18, 12, 980],
          },
          {
            color: '#6fffe9',
            kind: 'plane',
            opacity: 0.22,
            physics: 'decorative',
            position: [0, 940, 0],
            rotation: [-Math.PI / 2, 0, 0],
            size: [660, 660],
            transparent: true,
          },
        ],
        showCrownBeacon: false,
        showFrontWing: false,
        showHorizontalCap: false,
        showMegaVerticalSpines: false,
        showRearSpine: false,
        showSideFloorBands: false,
        showSideInset: false,
        showSignatureBand: false,
        skipBase: true,
      },
      planningZone: 'left-district',
      role: 'structural',
      sections: ['left'],
      size: [1, 1, 1],
    },
  ];
}

function buildCenterSkyCompassMasses(): CityMass[] {
  const center: [number, number, number] = [2200, 0, -960];
  const accent = '#8ee8ff';

  return [
    {
      color: '#0c1c2b',
      decorPolicy: 'none',
      id: 'center-sky-compass-primitive-rig',
      planningSource: createCenterSpinePlanningSource('buildCenterSkyCompassMasses', CENTER_SKY_COMPASS_SOURCE_KIND),
      position: center,
      renderIntent: {
        emissive: accent,
        emissiveIntensity: 0.02,
        primitives: [
          {
            color: '#6d8190',
            emissive: accent,
            emissiveIntensity: 0.01,
            kind: 'box',
            metalness: 0.14,
            physics: 'decorative',
            position: [0, 26, 0],
            roughness: 0.62,
            size: [620, 52, 620],
          },
          {
            color: '#7f95a3',
            emissive: accent,
            emissiveIntensity: 0.012,
            kind: 'box',
            metalness: 0.16,
            physics: 'decorative',
            position: [-230, 640, 0],
            roughness: 0.58,
            size: [72, 1280, 112],
          },
          {
            color: '#7f95a3',
            emissive: accent,
            emissiveIntensity: 0.012,
            kind: 'box',
            metalness: 0.16,
            physics: 'decorative',
            position: [230, 640, 0],
            roughness: 0.58,
            size: [72, 1280, 112],
          },
          {
            color: '#748998',
            emissive: accent,
            emissiveIntensity: 0.012,
            kind: 'box',
            metalness: 0.16,
            physics: 'decorative',
            position: [0, 640, -230],
            roughness: 0.58,
            size: [112, 1280, 72],
          },
          {
            color: '#748998',
            emissive: accent,
            emissiveIntensity: 0.012,
            kind: 'box',
            metalness: 0.16,
            physics: 'decorative',
            position: [0, 640, 230],
            roughness: 0.58,
            size: [112, 1280, 72],
          },
          {
            color: '#9eb8c7',
            emissive: accent,
            emissiveIntensity: 0.03,
            height: 3200,
            kind: 'cylinder',
            metalness: 0.24,
            physics: 'decorative',
            position: [0, 1720, 0],
            radialSegments: 24,
            radiusBottom: 68,
            radiusTop: 42,
            roughness: 0.3,
          },
          {
            color: '#c8e7f3',
            emissive: accent,
            emissiveIntensity: 0.035,
            height: 58,
            kind: 'cylinder',
            metalness: 0.24,
            opacity: 0.92,
            physics: 'decorative',
            position: [0, 3050, 0],
            radialSegments: 64,
            radiusBottom: 440,
            radiusTop: 390,
            roughness: 0.24,
            transparent: true,
          },
          {
            color: '#dffbff',
            emissive: accent,
            emissiveIntensity: 0.06,
            height: 1700,
            kind: 'cylinder',
            metalness: 0.3,
            physics: 'decorative',
            position: [0, 3925, 0],
            radialSegments: 18,
            radiusBottom: 28,
            radiusTop: 7,
            roughness: 0.2,
          },
          {
            color: '#ffffff',
            emissive: accent,
            emissiveIntensity: 0.05,
            height: 34,
            kind: 'cylinder',
            metalness: 0.28,
            opacity: 0.86,
            physics: 'decorative',
            position: [0, 4780, 0],
            radialSegments: 48,
            radiusBottom: 170,
            radiusTop: 130,
            roughness: 0.22,
            transparent: true,
          },
          {
            color: '#91e8ff',
            emissive: accent,
            emissiveIntensity: 0.03,
            kind: 'box',
            metalness: 0.2,
            physics: 'decorative',
            position: [0, 3068, 0],
            roughness: 0.34,
            size: [980, 18, 24],
          },
          {
            color: '#91e8ff',
            emissive: accent,
            emissiveIntensity: 0.03,
            kind: 'box',
            metalness: 0.2,
            physics: 'decorative',
            position: [0, 3088, 0],
            roughness: 0.34,
            size: [24, 18, 980],
          },
        ],
        showCrownBeacon: false,
        showFrontWing: false,
        showHorizontalCap: false,
        showMegaVerticalSpines: false,
        showRearSpine: false,
        showSideFloorBands: false,
        showSideInset: false,
        showSignatureBand: false,
        skipBase: true,
      },
      planningZone: 'right-district',
      role: 'structural',
      sections: ['right'],
      size: [1, 1, 1],
    },
  ];
}

export function buildCenterSpineZoneGeometry(context: ExpoZonePlannerContext) {
  const planes = [
    ...context.geometry.promenadeAxisPlanes.filter(isCenterSpinePlane),
    ...context.geometry.showcasePlazas.filter(isCenterSpinePlane),
    ...context.geometry.boothForecourtPlanes.filter(isCenterSpinePlane),
  ];

  const masses = [
    ...context.geometry.showcaseMasses.filter(isCenterSpineMass),
    ...context.geometry.discoveryLandmarkMasses.filter(isCenterSpineMass),
    ...context.geometry.discoverySupportMasses.filter(isCenterSpineMass),
    ...context.geometry.observatoryMasses.filter(isCenterSpineMass),
    ...context.geometry.signatureMasses.filter(isCenterSpineMass),
    ...context.geometry.skybridgeMasses.filter(isCenterSpineMass),
    ...buildSkyMarketSpineMasses(),
    ...buildAiReactorCoreMasses(),
    ...buildCenterSkyCompassMasses(),
  ];

  return {
    masses,
    planes,
    towers: [],
  };
}
