import type { ModularHomeModuleId, ModularHomeProductId } from '../modularHomeProducts';
import type { ModularHomeComponent, ModularHomeComponentId } from './types';

export const MODULAR_HOME_COMPONENT_BOM_DISCLAIMER = 'Preview component BOM · production verification required';
export const MODULAR_HOME_MANUFACTURING_BOM_DISCLAIMER = 'Manufacturing BOM preview · production cut list requires engineering verification.';

export const MODULAR_HOME_COMPONENTS = [
  {
    id: 'timber-wall-panel-system',
    baseUnitCost: 64,
    category: 'wallPanel',
    compatibleModuleTypes: ['living', 'bedroom', 'bathroomCore', 'technical'],
    label: 'Timber wall panel system',
    laborUnitCost: 28,
    notes: 'Preview wall panel quantity derived from module perimeter and clear height.',
    quantityFormula: 'module perimeter x module height x module quantity x 0.86 opening factor',
    unit: 'm2',
    visualToken: 'timber-wall-panels',
    wasteFactor: 0.08,
  },
  {
    id: 'timber-floor-cassette-system',
    baseUnitCost: 58,
    category: 'floorCassette',
    compatibleModuleTypes: ['living', 'bedroom', 'bathroomCore', 'technical'],
    label: 'Timber floor cassette',
    laborUnitCost: 18,
    notes: 'Preview floor cassette area follows each transport module footprint.',
    quantityFormula: 'module width x module length x module quantity',
    unit: 'm2',
    visualToken: 'timber-floor-cassette',
    wasteFactor: 0.06,
  },
  {
    id: 'flat-roof-cassette-system',
    baseUnitCost: 74,
    category: 'roofCassette',
    compatibleModuleTypes: ['roof'],
    label: 'Flat roof cassette',
    laborUnitCost: 24,
    notes: 'Flat roof package placeholder before engineering-specific build-up.',
    quantityFormula: 'roof module width x roof module length',
    unit: 'm2',
    visualToken: 'flat-roof-cassette',
    wasteFactor: 0.07,
  },
  {
    id: 'pitched-roof-cassette-system',
    baseUnitCost: 82,
    category: 'roofCassette',
    compatibleModuleTypes: ['roof'],
    label: 'Pitched roof cassette',
    laborUnitCost: 29,
    notes: 'Preview pitched roof area includes a simplified slope factor.',
    quantityFormula: 'roof module width x roof module length x 1.18 pitch factor',
    unit: 'm2',
    visualToken: 'pitched-roof-cassette',
    wasteFactor: 0.09,
  },
  {
    id: 'natural-timber-facade-boarding',
    baseUnitCost: 36,
    category: 'facadeBoarding',
    compatibleModuleTypes: ['facade'],
    label: 'Natural timber facade boarding',
    laborUnitCost: 18,
    notes: 'Baseline timber cladding package for product preview.',
    quantityFormula: 'facade module width x facade module height x 4 elevations',
    unit: 'm2',
    visualToken: 'natural-timber-boarding',
    wasteFactor: 0.1,
  },
  {
    id: 'dark-thermo-facade-boarding',
    baseUnitCost: 48,
    category: 'facadeBoarding',
    compatibleModuleTypes: ['facade'],
    label: 'Dark thermo wood facade boarding',
    laborUnitCost: 20,
    notes: 'Premium exterior expression used by dark facade option.',
    quantityFormula: 'facade module width x facade module height x 4 elevations',
    unit: 'm2',
    visualToken: 'dark-thermo-boarding',
    wasteFactor: 0.1,
  },
  {
    id: 'light-painted-facade-boarding',
    baseUnitCost: 42,
    category: 'facadeBoarding',
    compatibleModuleTypes: ['facade'],
    label: 'Light painted facade boarding',
    laborUnitCost: 21,
    notes: 'Painted facade package for residential-friendly presentation.',
    quantityFormula: 'facade module width x facade module height x 4 elevations',
    unit: 'm2',
    visualToken: 'light-painted-boarding',
    wasteFactor: 0.11,
  },
  {
    id: 'standard-window-unit',
    baseUnitCost: 430,
    category: 'windowUnit',
    compatibleModuleTypes: ['living', 'bedroom', 'bathroomCore', 'technical'],
    label: 'Window unit package',
    laborUnitCost: 120,
    notes: 'Preview window count is derived from module type.',
    quantityFormula: 'module type window count x module quantity',
    unit: 'piece',
    visualToken: 'standard-window-unit',
    wasteFactor: 0.02,
  },
  {
    id: 'panoramic-window-unit',
    baseUnitCost: 980,
    category: 'windowUnit',
    compatibleModuleTypes: ['living', 'bedroom'],
    label: 'Panoramic glazing unit package',
    laborUnitCost: 220,
    notes: 'Larger glazing preview package; final opening, solar-gain and transport review required.',
    quantityFormula: 'selected panoramic window package x module type window count',
    unit: 'piece',
    visualToken: 'panoramic-window-unit',
    wasteFactor: 0.04,
  },
  {
    id: 'corner-glazing-unit',
    baseUnitCost: 1320,
    category: 'windowUnit',
    compatibleModuleTypes: ['living', 'bedroom'],
    label: 'Corner glazing unit package',
    laborUnitCost: 310,
    notes: 'Corner glazing preview package; production corner opening and thermal bridge review required.',
    quantityFormula: 'selected corner glazing package x module type window count',
    unit: 'piece',
    visualToken: 'corner-glazing-unit',
    wasteFactor: 0.06,
  },
  {
    id: 'privacy-window-unit',
    baseUnitCost: 560,
    category: 'windowUnit',
    compatibleModuleTypes: ['living', 'bedroom', 'bathroomCore', 'technical'],
    label: 'Compact/privacy glazing unit',
    laborUnitCost: 145,
    notes: 'Smaller privacy-oriented glazing preview package for compact and service layouts.',
    quantityFormula: 'selected privacy window package x reduced module type window count',
    unit: 'piece',
    visualToken: 'privacy-window-unit',
    wasteFactor: 0.03,
  },
  {
    id: 'entry-door-unit',
    baseUnitCost: 760,
    category: 'doorUnit',
    compatibleModuleTypes: ['living', 'technical'],
    label: 'Entry door unit',
    laborUnitCost: 180,
    notes: 'Main external door package for entry-facing module.',
    quantityFormula: 'one entry door for each living or sauna/technical core module',
    unit: 'piece',
    visualToken: 'entry-door-unit',
    wasteFactor: 0.02,
  },
  {
    id: 'terrace-slider-door-unit',
    baseUnitCost: 2400,
    category: 'doorUnit',
    compatibleModuleTypes: ['living', 'technical'],
    label: 'Terrace slider door unit',
    laborUnitCost: 480,
    notes: 'Slider package placeholder; final threshold, drainage and weatherproofing detail required.',
    quantityFormula: 'selected terrace slider package x entry-facing module count',
    unit: 'piece',
    visualToken: 'terrace-slider-door-unit',
    wasteFactor: 0.05,
  },
  {
    id: 'premium-glazed-entry-door-unit',
    baseUnitCost: 1850,
    category: 'doorUnit',
    compatibleModuleTypes: ['living', 'technical'],
    label: 'Premium glazed entry door unit',
    laborUnitCost: 360,
    notes: 'Premium glazed entry placeholder; final hardware, thermal and security review required.',
    quantityFormula: 'selected premium glazed entry package x entry-facing module count',
    unit: 'piece',
    visualToken: 'premium-glazed-entry-door-unit',
    wasteFactor: 0.04,
  },
  {
    id: 'bathroom-wet-core-kit',
    baseUnitCost: 5200,
    category: 'bathroomCore',
    compatibleModuleTypes: ['bathroomCore'],
    label: 'Bathroom wet core kit',
    laborUnitCost: 2100,
    notes: 'Preview wet core package; final plumbing and compliance require review.',
    quantityFormula: 'one package per bathroom core module quantity',
    unit: 'package',
    visualToken: 'bathroom-wet-core',
    wasteFactor: 0.04,
  },
  {
    id: 'compact-kitchen-line',
    baseUnitCost: 720,
    category: 'kitchenLine',
    compatibleModuleTypes: ['living'],
    label: 'Compact kitchen line',
    laborUnitCost: 190,
    notes: 'Compact kitchen run for the Compact Timber 40 layout.',
    quantityFormula: '2.8 linear meters x compact living module quantity',
    unit: 'linearM',
    visualToken: 'compact-kitchen-line',
    wasteFactor: 0.05,
  },
  {
    id: 'family-kitchen-line',
    baseUnitCost: 760,
    category: 'kitchenLine',
    compatibleModuleTypes: ['living'],
    label: 'Family kitchen line',
    laborUnitCost: 210,
    notes: 'Longer kitchen run for Family Timber 80.',
    quantityFormula: '4.2 linear meters x family living module quantity',
    unit: 'linearM',
    visualToken: 'family-kitchen-line',
    wasteFactor: 0.05,
  },
  {
    id: 'small-terrace-deck-system',
    baseUnitCost: 72,
    category: 'terraceDeck',
    compatibleModuleTypes: ['terrace'],
    label: 'Front deck system',
    laborUnitCost: 26,
    notes: 'Front deck package for first offer conversations.',
    quantityFormula: 'terrace module width x terrace module length',
    unit: 'm2',
    visualToken: 'front-deck-system',
    wasteFactor: 0.08,
  },
  {
    id: 'side-terrace-deck-system',
    baseUnitCost: 76,
    category: 'terraceDeck',
    compatibleModuleTypes: ['terrace'],
    label: 'Side terrace deck system',
    laborUnitCost: 28,
    notes: 'Side terrace package for side access and outdoor utility use.',
    quantityFormula: 'side terrace module width x side terrace module length',
    unit: 'm2',
    visualToken: 'side-terrace-deck',
    wasteFactor: 0.08,
  },
  {
    id: 'extended-terrace-deck-system',
    baseUnitCost: 76,
    category: 'terraceDeck',
    compatibleModuleTypes: ['terrace'],
    label: 'Extended terrace deck system',
    laborUnitCost: 28,
    notes: 'Larger terrace package; final foundation interface requires review.',
    quantityFormula: 'terrace module width x terrace module length',
    unit: 'm2',
    visualToken: 'extended-terrace-deck',
    wasteFactor: 0.09,
  },
  {
    id: 'covered-terrace-deck-system',
    baseUnitCost: 82,
    category: 'terraceDeck',
    compatibleModuleTypes: ['terrace'],
    label: 'Covered terrace deck system',
    laborUnitCost: 32,
    notes: 'Covered terrace deck allowance; final support and foundation interface requires review.',
    quantityFormula: 'covered terrace module width x covered terrace module length',
    unit: 'm2',
    visualToken: 'covered-terrace-deck',
    wasteFactor: 0.1,
  },
  {
    id: 'covered-terrace-roof-placeholder',
    baseUnitCost: 96,
    category: 'roofCassette',
    compatibleModuleTypes: ['terrace'],
    label: 'Covered terrace roof placeholder',
    laborUnitCost: 38,
    notes: 'Placeholder roof/post package for covered terrace preview; production structural review required.',
    quantityFormula: 'covered terrace roof area placeholder',
    unit: 'm2',
    visualToken: 'covered-terrace-roof-placeholder',
    wasteFactor: 0.1,
  },
  {
    id: 'foundation-pad-set',
    baseUnitCost: 92,
    category: 'foundationPad',
    compatibleModuleTypes: ['living', 'bedroom', 'bathroomCore', 'technical', 'terrace'],
    label: 'Foundation pad placeholder',
    laborUnitCost: 34,
    notes: 'Placeholder only; site-specific foundation is outside preview estimate.',
    quantityFormula: 'module footprint m2 x module quantity',
    unit: 'm2',
    visualToken: 'foundation-pad-placeholder',
    wasteFactor: 0.04,
  },
  {
    id: 'interior-plywood-finish',
    baseUnitCost: 26,
    category: 'interiorFinish',
    compatibleModuleTypes: ['living', 'bedroom', 'bathroomCore', 'technical'],
    label: 'Interior plywood finish',
    laborUnitCost: 16,
    notes: 'Preview interior finish surface, excluding final room-by-room specification.',
    quantityFormula: 'module interior wall area x finish factor',
    unit: 'm2',
    visualToken: 'interior-plywood-finish',
    wasteFactor: 0.09,
  },
  {
    id: 'standard-furniture-package',
    baseUnitCost: 2300,
    category: 'furniturePackage',
    compatibleModuleTypes: ['living', 'bedroom'],
    label: 'Standard furniture preview package',
    laborUnitCost: 260,
    notes: 'Simple furniture placeholder for commercial visualization.',
    quantityFormula: 'one package per living or bedroom module when finish is standard or premium',
    unit: 'package',
    visualToken: 'standard-furniture-package',
    wasteFactor: 0.02,
  },
  {
    id: 'premium-furniture-package',
    baseUnitCost: 4200,
    category: 'furniturePackage',
    compatibleModuleTypes: ['living', 'bedroom'],
    label: 'Premium furniture preview package',
    laborUnitCost: 390,
    notes: 'Premium interior placeholder; not a final furniture quote.',
    quantityFormula: 'one package per living or bedroom module when finish is premium',
    unit: 'package',
    visualToken: 'premium-furniture-package',
    wasteFactor: 0.03,
  },
  {
    id: 'sauna-bench-package',
    baseUnitCost: 3100,
    category: 'furniturePackage',
    compatibleModuleTypes: ['living'],
    label: 'Sauna bench package',
    laborUnitCost: 620,
    notes: 'Sauna-specific interior package for the wellness module preview.',
    quantityFormula: 'one sauna bench package per sauna core module',
    unit: 'package',
    visualToken: 'sauna-bench-package',
    wasteFactor: 0.04,
  },
] as const satisfies readonly ModularHomeComponent[];

const WINDOW_COMPONENT_IDS = [
  'standard-window-unit',
  'panoramic-window-unit',
  'corner-glazing-unit',
  'privacy-window-unit',
] as const satisfies readonly ModularHomeComponentId[];

const DOOR_COMPONENT_IDS = [
  'entry-door-unit',
  'terrace-slider-door-unit',
  'premium-glazed-entry-door-unit',
] as const satisfies readonly ModularHomeComponentId[];

export const MODULAR_HOME_MODULE_COMPONENT_IDS = {
  'compact-living-module': [
    'timber-wall-panel-system',
    'timber-floor-cassette-system',
    ...WINDOW_COMPONENT_IDS,
    ...DOOR_COMPONENT_IDS,
    'compact-kitchen-line',
    'foundation-pad-set',
    'interior-plywood-finish',
    'standard-furniture-package',
    'premium-furniture-package',
  ],
  'compact-bedroom-module': [
    'timber-wall-panel-system',
    'timber-floor-cassette-system',
    ...WINDOW_COMPONENT_IDS,
    'foundation-pad-set',
    'interior-plywood-finish',
    'standard-furniture-package',
    'premium-furniture-package',
  ],
  'bathroom-core-module': [
    'timber-wall-panel-system',
    'timber-floor-cassette-system',
    ...WINDOW_COMPONENT_IDS,
    'bathroom-wet-core-kit',
    'foundation-pad-set',
    'interior-plywood-finish',
  ],
  'family-living-module': [
    'timber-wall-panel-system',
    'timber-floor-cassette-system',
    ...WINDOW_COMPONENT_IDS,
    ...DOOR_COMPONENT_IDS,
    'family-kitchen-line',
    'foundation-pad-set',
    'interior-plywood-finish',
    'standard-furniture-package',
    'premium-furniture-package',
  ],
  'family-bedroom-module': [
    'timber-wall-panel-system',
    'timber-floor-cassette-system',
    ...WINDOW_COMPONENT_IDS,
    'foundation-pad-set',
    'interior-plywood-finish',
    'standard-furniture-package',
    'premium-furniture-package',
  ],
  'sauna-core-module': [
    'timber-wall-panel-system',
    'timber-floor-cassette-system',
    'standard-window-unit',
    'privacy-window-unit',
    ...DOOR_COMPONENT_IDS,
    'foundation-pad-set',
    'interior-plywood-finish',
    'sauna-bench-package',
  ],
  'roof-flat-module': [
    'flat-roof-cassette-system',
  ],
  'roof-pitched-module': [
    'pitched-roof-cassette-system',
  ],
  'facade-natural-timber': [
    'natural-timber-facade-boarding',
  ],
  'facade-dark-thermo': [
    'dark-thermo-facade-boarding',
  ],
  'facade-light-painted': [
    'light-painted-facade-boarding',
  ],
  'terrace-small-module': [
    'small-terrace-deck-system',
    'foundation-pad-set',
  ],
  'terrace-side-module': [
    'side-terrace-deck-system',
    'foundation-pad-set',
  ],
  'terrace-extended-module': [
    'extended-terrace-deck-system',
    'foundation-pad-set',
  ],
  'terrace-covered-placeholder-module': [
    'covered-terrace-deck-system',
    'covered-terrace-roof-placeholder',
    'foundation-pad-set',
  ],
} as const satisfies Record<ModularHomeModuleId, readonly ModularHomeComponentId[]>;

export const MODULAR_HOME_PRODUCT_COMPONENT_LIBRARY = {
  'compact-timber-40': [
    'timber-wall-panel-system',
    'timber-floor-cassette-system',
    'pitched-roof-cassette-system',
    'natural-timber-facade-boarding',
    ...WINDOW_COMPONENT_IDS,
    ...DOOR_COMPONENT_IDS,
    'bathroom-wet-core-kit',
    'compact-kitchen-line',
    'small-terrace-deck-system',
    'side-terrace-deck-system',
    'covered-terrace-deck-system',
    'covered-terrace-roof-placeholder',
    'foundation-pad-set',
    'interior-plywood-finish',
    'standard-furniture-package',
  ],
  'family-timber-80': [
    'timber-wall-panel-system',
    'timber-floor-cassette-system',
    'pitched-roof-cassette-system',
    'natural-timber-facade-boarding',
    ...WINDOW_COMPONENT_IDS,
    ...DOOR_COMPONENT_IDS,
    'bathroom-wet-core-kit',
    'family-kitchen-line',
    'extended-terrace-deck-system',
    'side-terrace-deck-system',
    'covered-terrace-deck-system',
    'covered-terrace-roof-placeholder',
    'foundation-pad-set',
    'interior-plywood-finish',
    'standard-furniture-package',
  ],
  'sauna-cabin-25': [
    'timber-wall-panel-system',
    'timber-floor-cassette-system',
    'flat-roof-cassette-system',
    'dark-thermo-facade-boarding',
    'standard-window-unit',
    'privacy-window-unit',
    ...DOOR_COMPONENT_IDS,
    'bathroom-wet-core-kit',
    'small-terrace-deck-system',
    'side-terrace-deck-system',
    'covered-terrace-deck-system',
    'covered-terrace-roof-placeholder',
    'foundation-pad-set',
    'interior-plywood-finish',
    'sauna-bench-package',
  ],
} as const satisfies Record<ModularHomeProductId, readonly ModularHomeComponentId[]>;

export function getComponentById(id: ModularHomeComponentId): ModularHomeComponent | undefined {
  return MODULAR_HOME_COMPONENTS.find((component) => component.id === id);
}

export function getComponentIdsForModule(moduleId: ModularHomeModuleId): readonly ModularHomeComponentId[] {
  return MODULAR_HOME_MODULE_COMPONENT_IDS[moduleId] ?? [];
}
