[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=280BB0A54676273C62AD2882BF48BE92
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=


[/Script/EngineSettings.GameMapsSettings]
GlobalDefaultGameMode=/Game/Warpala/Blueprints/BP_WarpalaGameMode.BP_WarpalaGameMode_C
GameDefaultMap=/Game/Warpala/Maps/WarpalaCity_Main
EditorStartupMap=/Game/Warpala/Maps/WarpalaCity_Main

[CoreRedirects]
+ClassRedirects=(OldName="/Script/WarpalaSimulation.CityGenerator",NewName="/Script/WarpalaCity.CityGenerator")

[/Script/Engine.StreamingSettings]
s.UseBackgroundLevelStreaming=False


[/Script/PixelStreaming.PixelStreamingSettings]
; 8888 is reserved for the Pixel Streaming streamer/signaling chain.
DefaultStreamerPort=8888
bDecoupleFrameRate=true
WebRTCFps=60
WebRTCMaxBitrate=20000
WebRTCMinBitrate=1000
NegotiateCodecs=VP8,H264

